name = "PrunklesBaseModpack"
author = "Prunkles"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "182f90cf3c54d327a55b104f63c052a83dae37de61a8fd6957b5522e6a474be7"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
